# Global configuration for your project
paths:
  applies_dir: "/home/amir/Work/Personal/Jobuine/applies"
  store_file: "/home/amir/Work/Personal/Jobuine/applies/store.xlsx"
current_apply_dir: "/home/amir/Work/Personal/Jobuine/applies/2025_11_10/apl_test"
