[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jobuine"
version = "0.1.0"
description = "Jobuine CLI"
dependencies = []

[project.scripts]
jobuine = "cli.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]
